# file: normal_compose.yaml
# image: normal_app
version: '3'
services:
  app:
    image: normal_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./vinnity:/path/to/copy/vinnity  # 'vinnity' klasörünü hedef dizine kopyalar
    command: |
      bash -c "pip install -r requirements.txt"  # Gerekli bağımlılıkları yükler ve programı başlatır
